import type { Resource, TagWithCount } from "./types"

/** Default library resources synced from the August 2026 course set. */
export const RESOURCES_DATA_VERSION = "2026-08-24-aug-new"

export type { Resource, ResourceType, TagWithCount } from "./types"

/** A tag only counts as popular once more than this many resources use it. */
export const POPULAR_TAG_MIN_REFERENCES = 5

export const resources: Resource[] = [
  {
    id: "1787598069356-zpdkw7prt",
    title: "A Framework of User Experience Principles for Human-AI Agent Interaction in the Workplace",
    type: "pdf",
    url: "https://arxiv.org/pdf/2607.19941",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "As AI agents become integral to business workflows, establishing guiding user experience principles is crucial for ensuring user trust and successful adoption. Using a multi-method approach that combines a participatory design workshop, paper-and-pencil exercises, expert review, meta-analysis, and in-depth interviews, the authors identify and validate a design framework of eight core UX principles for human-AI agent interaction in the workplace, each with measurable criteria. Published in the proceedings of Mensch und Computer 2026, this is one of the first empirically validated principle sets aimed specifically at enterprise agentic systems, and it makes a good counterpart to the older Microsoft and Google human-AI guideline sets.",
    tags: ["Agents","Ai Principles","Methodology"],
    dateAdded: "2026-08-24",
    author: "Paimann, Valarini and Juhl (SAP SE)",
    year: 2026,
  },
  {
    id: "1787598069357-lx1gp04jj",
    title: "Human Oversight of Agentic Systems in Practice",
    type: "pdf",
    url: "https://arxiv.org/pdf/2606.05391",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "Autonomous software agents promise productivity gains but make mistakes and exhibit novel failure modes, making human oversight central to successful human-agent collaboration. Existing research on agent oversight is largely conceptual; this study provides empirical anchors, drawing on interviews with 17 experienced developers to examine what forms of oversight work people actually perform, when, and how. The authors identify four forms of emergent oversight work - a priori control, co-planning, real-time monitoring, and post hoc review - showing that oversight is not only reactive and retrospective but also preventative and proactive, and they document the situated challenges and heuristics practitioners have developed. Directly useful for anyone designing handoff, review, and intervention moments in agentic products.",
    tags: ["Agents","Ai Principles","Qualitative Methods"],
    dateAdded: "2026-08-24",
    author: "Dhanorkar, Passi and Vorvoreanu",
    year: 2026,
  },
  {
    id: "1787598069358-rqr08dh6q",
    title: "On the Regulatory Potential of User Interfaces for AI Agent Governance",
    type: "pdf",
    url: "https://arxiv.org/pdf/2512.00742",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "AI agents that act autonomously over extended time horizons require governance interventions to curb their risks. Where most proposals target system-level safeguards or agent infrastructure, this paper explores regulating the user interface itself as a way of enforcing transparency and behavioral requirements. The authors analyze 22 existing agentic systems to identify the UI elements that carry the weight of human-agent communication, then synthesize six high-level interaction design patterns with regulatory potential - for example, requiring that agent memory be user-editable - and close with policy recommendations. A rare paper that puts interface design squarely at the center of AI policy.",
    tags: ["Agents","Ai Principles","Xai"],
    dateAdded: "2026-08-24",
    author: "Feng, Kim, Pang, Huq, August and Zhang (University of Washington)",
    year: 2025,
  },
  {
    id: "1787598069359-inc4q8lfn",
    title: "Generative UI: LLMs are Effective UI Generators",
    type: "pdf",
    url: "https://arxiv.org/pdf/2604.09577",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "AI models excel at creating content but typically render it through static, predefined interfaces - most often a markdown wall of text. This Google Research paper demonstrates that properly prompted modern LLMs can reliably produce high-quality custom interfaces for a wide range of prompts, generating complete interactive web pages that substantially outperform standard markdown output in human preference evaluations. The authors show the capability is emergent in newer models and release PAGEN, a benchmark dataset for evaluating generative UI systems. Essential background for the shift from designing fixed screens to designing the generative system that produces them.",
    tags: ["LLM","Prototyping","Evaluation"],
    dateAdded: "2026-08-24",
    author: "Leviathan, Valevski, Kalman, Matias et al. (Google Research)",
    year: 2026,
  },
  {
    id: "1787598069360-nm4aog8ce",
    title: "The Emerging Use of GenAI for UX Research in Software Development: Challenges and Opportunities",
    type: "pdf",
    url: "https://arxiv.org/pdf/2512.15944",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "An interview study with 21 practitioners examining how generative AI is reshaping qualitative research practice inside product teams. The authors surface a central organizational tension: UX researchers expressed limited trust in AI-generated results while product managers often overestimated AI capabilities, creating pressure to compress research timelines. The paper validates an alternative AI analysis method aligned with human analytic processes and offers concrete guidance for responsibly folding AI into development workflows. A good complement to the codebook and thematic-analysis papers already in the collection, because it addresses the politics of AI-assisted research rather than only the method.",
    tags: ["User Research","Qualitative Methods","LLM"],
    dateAdded: "2026-08-24",
    author: "Candello, Geyer, Kunde, Muller, He et al. (IBM Research)",
    year: 2025,
  },
  {
    id: "1787598069361-vejz5gmli",
    title: "Learning to Trust: How Humans Mentally Recalibrate AI Confidence Signals",
    type: "pdf",
    url: "https://arxiv.org/pdf/2603.22634",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "Productive human-AI collaboration requires appropriate reliance, yet contemporary AI systems are often miscalibrated, exhibiting systematic overconfidence or underconfidence. In a behavioral experiment with 200 participants across four AI calibration conditions, the authors show robust learning: people significantly improve their accuracy, discrimination, and calibration alignment over 50 trials. A computational model explains the dynamics through updates to baseline trust and confidence sensitivity, with asymmetric learning rates that prioritize the most informative errors - but the authors also identify a boundary condition where a reverse confidence mapping defeats many users. Practical implications for how confidence, uncertainty, and error are surfaced in an interface.",
    tags: ["Xai","Evaluation","Ai Principles"],
    dateAdded: "2026-08-24",
    author: "ZhaoBin Li and Mark Steyvers (UC Irvine)",
    year: 2026,
  },
  {
    id: "1787598069362-vvgr9otpn",
    title: "Overreliance in Writing Tasks: Similarity-Based Measures of AI Influence and a Reflective Writing Interface",
    type: "pdf",
    url: "https://arxiv.org/pdf/2605.15322",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "As generative AI systems become proficient at simulating human-like, well-reasoned text, users may attribute authority to AI outputs in ways that reshape how they engage with writing and reasoning. This mixed-methods study with 47 participants measures the textual overlap between AI suggestions and participants' own writing across analysis and synthesis tasks, finding clear patterns of suggestion reuse. The authors then design an interactive writing interface that displays real-time metrics on AI suggestion adoption, and a follow-up think-aloud study suggests the interface increases users' awareness of how AI output is being incorporated. Both an empirical method for studying overreliance and a concrete interface intervention - useful as a classroom exercise on AI literacy.",
    tags: ["LLM","Ai Literacy","Evaluation"],
    dateAdded: "2026-08-24",
    author: "Vitor H. A. Welzel and Nicholas Vincent",
    year: 2026,
  },
  {
    id: "1787598069363-5p2flbjyk",
    title: "Human Oversight-by-Design for Accessible Generative Interfaces",
    type: "pdf",
    url: "https://arxiv.org/pdf/2602.13745",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "LLM-generated interfaces are increasingly used in high-consequence workflows such as healthcare communication, where how information is presented shapes downstream action, and where accessibility is a precondition for meaningful oversight rather than a nice-to-have. The authors propose oversight-by-design: embedding human judgment across the pipeline as an architectural commitment, implemented through escalation policies and explicit UI controls for risk signalling and intervention. Automated checks flag readability, semantic fidelity, factual consistency, and standards-based accessibility violations, escalating to mandatory human-in-the-loop review when thresholds are breached, while human-on-the-loop supervision tunes policies and detects drift over time. One of the few papers connecting accessibility, generative UI, and AI governance in a single design framework.",
    tags: ["Ai Principles","Agents","Methodology"],
    dateAdded: "2026-08-24",
    author: "Jerry, Moreno and Martinez (Universidad Carlos III de Madrid)",
    year: 2026,
  },
  {
    id: "1787598069364-aa6t1bpb9",
    title: "Can Large Language Models Reliably Code Qualitative Data? A Benchmark Study Against Human Expert Adjudication",
    type: "pdf",
    url: "https://arxiv.org/pdf/2606.26541",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "A large benchmark study testing 46 different LLMs against expert human coding across roughly 48,300 coding instances drawn from 150 humanitarian interview transcripts, evaluated with Krippendorff's alpha, discrepancy analysis, and qualitative assessment. Multiple models reach reliability levels comparable to experienced human coders when applying a structured codebook, but performance is uneven on the hardest categories - recognizing discrimination, complex needs hierarchies, and needs expressed indirectly. The authors conclude that LLMs can expand analytical capacity but require structured prompts, reasoning-enabled configurations, and tiered human oversight rather than serving as substitutes for human judgment. The most rigorous evidence base yet for the AI-assisted qualitative coding workflows in this collection.",
    tags: ["Qualitative Methods","Data Analysis","LLM"],
    dateAdded: "2026-08-24",
    author: "Marston, Kreutzer, Garnier, Boone, Pham and Vinck",
    year: 2026,
  },
  {
    id: "1787598069365-muoai3rdi",
    title: "The Siren Song of LLMs: How Users Perceive and Respond to Dark Patterns in Large Language Models",
    type: "pdf",
    url: "https://arxiv.org/pdf/2509.10830",
    thumbnail: "/pdf-thumbnail.jpg",
    summary: "Large language models can influence users through conversation itself, creating new forms of dark patterns that the existing deceptive-design literature does not cover. Drawing on prior work and AI incident reports, the authors define LLM dark patterns as manipulative or deceptive behaviors enacted in dialogue and identify five categories with real-world examples. A scenario-based study with 34 participants compared manipulative and neutral LLM responses, finding that recognition hinged on conversational cues such as exaggerated agreement, biased framing, or privacy intrusions - though participants often normalized these behaviors as ordinary helpfulness. Presented at CHI 2026, with implications for design, advocacy, and governance around user autonomy.",
    tags: ["Ai Principles","LLM","Examples"],
    dateAdded: "2026-08-24",
    author: "Shi, Xiao, Hu, Shen and Shen (CHI 2026)",
    year: 2026,
  },
  {
    id: "1787598069366-k3utrghlz",
    title: "The Shape of AI - UX Patterns for Artificial Intelligence",
    type: "link",
    url: "https://www.shapeof.ai/",
    thumbnail: "/url-thumbnail.jpg",
    summary: "A continuously updated pattern library documenting how user experience is evolving alongside AI, created by Emily Campbell. Patterns are organized into six families - Wayfinders, Inputs, Tuners, Governors, Trust Builders and Identifiers - each with definitions, UI examples from shipping products, and guidance on when the pattern helps or hurts. The Governors and Trust Builders sections in particular cover the control and confidence problems that agentic products keep running into. Shared under Creative Commons, with an accompanying newsletter and Slack community, this is the closest thing the field has to a canonical AI interface pattern reference.",
    tags: ["Ai Principles","Examples","Prototyping"],
    dateAdded: "2026-08-24",
    author: "Emily Campbell",
    year: 2026,
  },
  {
    id: "1787598069367-mcgj3h5cz",
    title: "Agentic Design - UI/UX and Human-AI Interaction Patterns",
    type: "link",
    url: "https://agentic-design.ai/patterns/ui-ux-patterns",
    thumbnail: "/url-thumbnail.jpg",
    summary: "A catalog of 32 interface patterns for autonomous and semi-autonomous AI systems, ranging from foundational human-in-the-loop controls through generative UI, progressive disclosure of agent reasoning, and realtime voice agents. The organizing argument is that agent autonomy, decision-making, and uncertainty should be made visible to users rather than concealed behind a simple chat box - each pattern is documented with the problem it solves, implementation notes, and failure modes. Useful as a starting vocabulary for critique sessions, since it gives students concrete names for the moves an agentic interface can make.",
    tags: ["Agents","Examples","Ai Principles"],
    dateAdded: "2026-08-24",
    author: "Agentic Design",
    year: 2026,
  },
  {
    id: "1787598069368-kv1nehcv7",
    title: "One AI Output Is an Example, Not an Evaluation",
    type: "link",
    url: "https://www.nngroup.com/articles/eval-ai-output/",
    thumbnail: "/url-thumbnail.jpg",
    summary: "Because AI systems are nondeterministic and produce different outputs from identical inputs, judging them by inspecting a single result is a category error. Budiu argues that sound AI evaluation borrows directly from quantitative UX research: use multiple representative inputs, run each repeatedly, and report average performance with confidence intervals so that both quality and consistency are measured. The article is short and concrete enough to assign as a corrective to demo-driven thinking, and it gives design teams a defensible standard for claims about how well an AI feature works.",
    tags: ["Evaluation","Methodology","Data / Quantitative"],
    dateAdded: "2026-08-24",
    author: "Raluca Budiu, Nielsen Norman Group",
    year: 2026,
  },
  {
    id: "1787598069369-l0ne2cgh9",
    title: "How to Decide When an AI Tool Is Worth Keeping: The PROVE Framework",
    type: "link",
    url: "https://www.nngroup.com/articles/prove-framework/",
    thumbnail: "/url-thumbnail.jpg",
    summary: "A practical framework for deciding whether a specific AI tool actually improves a specific task, rather than adopting it under organizational pressure. PROVE walks through five assessment dimensions - Problem alignment, Risk, Output quality, Velocity, and Experience - and Sponheim demonstrates it end to end on a real workflow, drafting weekly research digests with an AI notebook tool. The result is a repeatable way to measure real tradeoffs and reach a defensible adoption or rejection decision, which makes it a good assignment structure for evaluating any AI tool in a course.",
    tags: ["Evaluation","Methodology","Ai Literacy"],
    dateAdded: "2026-08-24",
    author: "Caleb Sponheim, Nielsen Norman Group",
    year: 2026,
  },
  {
    id: "1787598069370-ozpscpgms",
    title: "Artificial Intelligence: Glossary",
    type: "link",
    url: "https://www.nngroup.com/articles/artificial-intelligence-glossary/",
    thumbnail: "/url-thumbnail.jpg",
    summary: "Plain-language definitions of more than 80 AI terms as they are actually used in product and design work, from foundational concepts like large language model and transformer through applied ones like prompt engineering, retrieval-augmented generation, and evals. Entries are cross-referenced to each other and to deeper articles, so it works both as a quick lookup and as a reading path. A good shared-vocabulary handout for a mixed-background cohort, and a way to keep terminology consistent across a course.",
    tags: ["Ai Literacy","LLM","Tutorial"],
    dateAdded: "2026-08-24",
    author: "Caleb Sponheim, Nielsen Norman Group",
    year: 2026,
  },
  {
    id: "1787598069371-96uwuciyh",
    title: "Generative UI: A Rich, Custom, Visual Interactive User Experience for Any Prompt",
    type: "link",
    url: "https://research.google/blog/generative-ui-a-rich-custom-visual-interactive-user-experience-for-any-prompt/",
    thumbnail: "/url-thumbnail.jpg",
    summary: "Google Research's introduction of generative UI, in which the model produces not just content but the interface, tools, and simulations that present it. The post walks through the implementation - Gemini with tool access, system instructions, and post-processing - and reports that human raters strongly preferred generated interfaces over standard LLM output. It also documents the rollout into the Gemini app's dynamic view and Search's AI Mode, which makes it the clearest account of generative UI moving from research demo into shipping products. Read alongside the Generative UI paper for the evaluation detail.",
    tags: ["LLM","Prototyping","Examples"],
    dateAdded: "2026-08-24",
    author: "Leviathan, Valevski, Natchu and Matias (Google Research)",
    year: 2025,
  },
  {
    id: "1787598069372-i1pxvj6kc",
    title: "Awesome Generative UI - Papers, Videos and Projects",
    type: "link",
    url: "https://awesomegenerativeui.com/papers",
    thumbnail: "/url-thumbnail.jpg",
    summary: "A curated, actively maintained hub for research and practice around AI-generated interfaces, aggregating foundational papers from Google Research, academic HCI studies, industry projects, protocol work such as A2UI and MCP Apps, and a companion library of demo videos and tutorials. Entries carry short descriptions and topic tags, so it functions as a reading list rather than a link dump. Most of the collection is dated 2026, which makes it the fastest way to stay current on a subfield that is moving faster than conference cycles.",
    tags: ["Information Stream","LLM","Prototyping"],
    dateAdded: "2026-08-24",
    author: "Awesome Generative UI",
    year: 2026,
  },
  {
    id: "1787598069373-7gxljn7ya",
    title: "The Capability Maturity Model for AI in Design",
    type: "link",
    url: "https://jakobnielsenphd.substack.com/p/ai-maturity",
    thumbnail: "/url-thumbnail.jpg",
    summary: "Nielsen proposes a six-level maturity framework for how organizations adopt AI in design work, running from Level 1, where AI is treated as administrative task support, through Level 5, where designers work natively in code, to Level 6, where the distinction between design time and runtime dissolves. His argument is that levels cannot be leapfrogged, because each builds interdependent capabilities across leadership strategy, culture, talent development, automation, and product design. Provocative and debatable in places, which is exactly what makes it good discussion material about where design practice is heading.",
    tags: ["Careers","Ai Principles","Methodology"],
    dateAdded: "2026-08-24",
    author: "Jakob Nielsen",
    year: 2026,
  },
  {
    id: "1787598069374-yd4ryiy6r",
    title: "Interaction Models: A Scalable Approach to Human-AI Collaboration",
    type: "link",
    url: "https://thinkingmachines.ai/blog/interaction-models/",
    thumbnail: "/url-thumbnail.jpg",
    summary: "A technical and conceptual argument that turn-based chat is the wrong substrate for real human-AI collaboration. Thinking Machines Lab describes interaction models that handle audio, video, and text natively in real time using time-aligned micro-turns of roughly 200 milliseconds, coordinating a foreground interaction model with an asynchronous background model to support interruption, verbal interjection, and simultaneous speech. Their claim is that interactivity should scale alongside intelligence, and the post is worth reading as a preview of what multimodal and voice interaction design will have to account for next.",
    tags: ["Multimodal Ai","Agents","Ai Principles"],
    dateAdded: "2026-08-24",
    author: "Thinking Machines Lab",
    year: 2026,
  },
  {
    id: "1787598069375-2acsf3nzh",
    title: "2026 AI Design Field Report",
    type: "link",
    url: "https://www.dive.club/ideas/2026-ai-design-field-report",
    thumbnail: "/url-thumbnail.jpg",
    summary: "A practitioner field report synthesizing interviews with design teams at companies including Shopify and Notion into six observations about how AI has changed day-to-day design work. Among them: AI use is now effectively mandatory at leading companies, designers increasingly ship functional prototypes rather than static mocks, teams fork production codebases to experiment, general-purpose coding agents have displaced standalone design-AI tools, and startup and enterprise workflows have diverged sharply. Useful as a reality check on job expectations and portfolio work, and a good counterweight to vendor marketing.",
    tags: ["Careers","Vibe Coding","Prototyping"],
    dateAdded: "2026-08-24",
    author: "Ridd and Stephen Haney, Dive Club",
    year: 2026,
  },
  {
    id: "1787598069376-jyeokvzeb",
    title: "Beyond Chat: What's Next for AI Design Patterns",
    type: "video",
    url: "https://www.youtube.com/watch?v=C19H4QimihM",
    thumbnail: "https://img.youtube.com/vi/C19H4QimihM/maxresdefault.jpg",
    summary: "Vitaly Friedman, editor-in-chief of Smashing Magazine, on why the chat box became the default AI interface and what replaces it. He works through concrete alternatives - structured inputs, progressive disclosure of model reasoning, editable outputs, and interfaces that let users steer rather than re-prompt - drawing on the pattern research behind his AI interface design course. A good pairing with the Shape of AI pattern library, since he explains the reasoning behind the patterns rather than just cataloging them.",
    tags: ["Ai Principles","Examples","Tutorial"],
    dateAdded: "2026-08-24",
    author: "Vitaly Friedman on Dive Club",
    year: 2026,
  },
  {
    id: "1787598069377-feg998e1w",
    title: "Design Patterns For AI Interfaces in 2026",
    type: "video",
    url: "https://www.youtube.com/watch?v=JU9z3RRzC_8",
    thumbnail: "https://img.youtube.com/vi/JU9z3RRzC_8/maxresdefault.jpg",
    summary: "A conference-length talk by Vitaly Friedman surveying the design patterns that have emerged for AI-driven interfaces, with a heavy emphasis on real product examples rather than speculation. He covers input design beyond the prompt box, showing model confidence and provenance, correction and undo affordances, and the specific places where AI features tend to erode user trust. Practical enough to use as a critique checklist for student projects.",
    tags: ["Ai Principles","Examples","Tutorial"],
    dateAdded: "2026-08-24",
    author: "Vitaly Friedman, George Labs",
    year: 2026,
  },
  {
    id: "1787598069378-qzzkee765",
    title: "Config 2026 Keynote with Dylan Field",
    type: "video",
    url: "https://www.youtube.com/watch?v=2ZCc4k_IV5w",
    thumbnail: "https://img.youtube.com/vi/2ZCc4k_IV5w/maxresdefault.jpg",
    summary: "Figma's opening keynote from Config 2026, laying out how the company sees the design tool changing as AI moves from a feature to the substrate of the workflow. Worth watching less for the product announcements than for the framing of what design work becomes when generation is cheap - where craft, judgment, and systems thinking concentrate. Useful context for the design systems and agentic workflow sessions from the same conference.",
    tags: ["Figma","Careers","Prototyping"],
    dateAdded: "2026-08-24",
    author: "Dylan Field, Figma",
    year: 2026,
  },
  {
    id: "1787598069379-w1dtznrrm",
    title: "Figma Deep Dive: Agents",
    type: "video",
    url: "https://www.youtube.com/watch?v=0HqSSIPZkbI",
    thumbnail: "https://img.youtube.com/vi/0HqSSIPZkbI/maxresdefault.jpg",
    summary: "A Config 2026 deep dive into how agents fit into design tooling - what they can plan, execute, and revise inside a design file, and where a human still has to make the call. Concrete demonstrations of delegation, review, and correction that map closely onto the human-oversight research in this collection. Good material for discussing what a well-designed agent handoff actually looks like in a tool people use daily.",
    tags: ["Agents","Figma","Examples"],
    dateAdded: "2026-08-24",
    author: "Figma",
    year: 2026,
  },
  {
    id: "1787598069380-pv4syib44",
    title: "Figma Deep Dive: Agentic Workflows and the MCP",
    type: "video",
    url: "https://www.youtube.com/watch?v=D5WUW9X_-L0",
    thumbnail: "https://img.youtube.com/vi/D5WUW9X_-L0/maxresdefault.jpg",
    summary: "How clarity at the start of a workflow determines whether an agentic system can do useful work, demonstrated through Figma's integration with the Model Context Protocol. The session shows how design context - components, tokens, structure, and intent - can be made legible to agents so that AI is applied with intentionality rather than guesswork. A practical entry point to context engineering for designers who do not think of themselves as engineers.",
    tags: ["Agents","Figma","Prompting Techniques"],
    dateAdded: "2026-08-24",
    author: "Figma",
    year: 2026,
  },
  {
    id: "1787598069381-k4458kujf",
    title: "Why AI Evals Are the Hottest New Skill for Product Builders",
    type: "video",
    url: "https://www.youtube.com/watch?v=BsWxPI9UM4c",
    thumbnail: "https://img.youtube.com/vi/BsWxPI9UM4c/maxresdefault.jpg",
    summary: "Hamel Husain and Shreya Shankar, creators of the most widely taken evals course, explain why systematic evaluation has become the core competency for anyone shipping AI features. They walk through error analysis on real production data, how to build a labeled dataset from actual failures, when LLM-as-judge is appropriate, and why generic benchmark scores tell you almost nothing about your own product. The clearest available introduction to a skill set that sits squarely between UX research and engineering.",
    tags: ["Evaluation","Methodology","LLM"],
    dateAdded: "2026-08-24",
    author: "Hamel Husain and Shreya Shankar on Lenny's Podcast",
    year: 2025,
  },
  {
    id: "1787598069382-91jm4k59i",
    title: "Outcome-Oriented Design: The Era of AI Design",
    type: "video",
    url: "https://www.youtube.com/watch?v=orvtAMGBgPE",
    thumbnail: "https://img.youtube.com/vi/orvtAMGBgPE/maxresdefault.jpg",
    summary: "Kate Moran and Sarah Gibbons on how UX strategy shifts when interfaces are generated rather than fixed. The argument is that designers move from crafting a single artifact to defining adaptive frameworks that respond to individual user goals, rather than optimizing for an averaged user. Four minutes, which makes it an efficient lecture opener before a longer discussion of generative UI.",
    tags: ["Ai Principles","Methodology","Careers"],
    dateAdded: "2026-08-24",
    author: "Kate Moran and Sarah Gibbons, Nielsen Norman Group",
    year: 2026,
  },
  {
    id: "1787598069383-18npxssbf",
    title: "GenUI: AI-Generated Interfaces",
    type: "video",
    url: "https://www.youtube.com/watch?v=4pbYHXAe7Tg",
    thumbnail: "https://img.youtube.com/vi/4pbYHXAe7Tg/maxresdefault.jpg",
    summary: "A short, clear explainer of generative UI - interfaces assembled in real time by a model rather than designed in advance - and what it means to move from designing for many to tailoring for the individual. Moran and Gibbons keep it grounded in what is actually shipping, which makes it a useful primer before reading the Google Research generative UI work. Pairs well with the Outcome-Oriented Design video from the same team.",
    tags: ["LLM","Prototyping","Examples"],
    dateAdded: "2026-08-24",
    author: "Kate Moran and Sarah Gibbons, Nielsen Norman Group",
    year: 2025,
  },
  {
    id: "1787598069384-1poa2vypi",
    title: "AI-Assisted Prototyping: Promise and Pitfalls",
    type: "video",
    url: "https://www.youtube.com/watch?v=XavthHrTjIY",
    thumbnail: "https://img.youtube.com/vi/XavthHrTjIY/maxresdefault.jpg",
    summary: "AI tools turn static designs into working prototypes fast, but speed can mask flaws - Megan Brown makes the case for treating these tools as exploration instruments rather than production shortcuts. She covers what gets lost when a prototype looks finished before the thinking is, and how to keep evaluation honest when the artifact is convincing. A useful caution to assign alongside the vibe coding material already in this collection.",
    tags: ["Prototyping","Vibe Coding","Evaluation"],
    dateAdded: "2026-08-24",
    author: "Megan Brown, Nielsen Norman Group",
    year: 2025,
  },
  {
    id: "1787598069385-j2fgynvel",
    title: "AI Strategy: 3 Key Questions",
    type: "video",
    url: "https://www.youtube.com/watch?v=Ku_AojKEaiQ",
    thumbnail: "https://img.youtube.com/vi/Ku_AojKEaiQ/maxresdefault.jpg",
    summary: "Caleb Sponheim argues that a defensible AI strategy comes down to answering three questions honestly: what is our core business, are we chasing real value or just the perception of it, and what specific problem are we actually trying to solve. Short and blunt, and effective at cutting through feature-driven AI roadmaps. Works well as a framing exercise before students propose AI features of their own.",
    tags: ["Careers","Methodology","Ai Literacy"],
    dateAdded: "2026-08-24",
    author: "Caleb Sponheim, Nielsen Norman Group",
    year: 2025,
  },
  {
    id: "1787598069386-8ns3esh8h",
    title: "Design Systems WTF #58: What Do the Config 2026 Announcements Mean for Design Systems?",
    type: "video",
    url: "https://www.youtube.com/watch?v=dPwjfYjuAXw",
    thumbnail: "https://img.youtube.com/vi/dPwjfYjuAXw/maxresdefault.jpg",
    summary: "A working discussion among design systems practitioners about what changes when AI agents become consumers of a design system rather than just humans. Topics include making component documentation machine-legible, what token and naming discipline buys you when a model is assembling interfaces, and where governance has to tighten. A good look at the unglamorous infrastructure work that determines whether AI-assisted design actually produces coherent output.",
    tags: ["Figma","Agents","Methodology"],
    dateAdded: "2026-08-24",
    author: "zeroheight",
    year: 2026,
  },
  {
    id: "1787598069387-v6spohaeg",
    title: "Generative UI at Thinking Machines Lab",
    type: "video",
    url: "https://www.youtube.com/watch?v=ly3GtaiRFyo",
    thumbnail: "https://img.youtube.com/vi/ly3GtaiRFyo/maxresdefault.jpg",
    summary: "A demonstration and explanation of generative interfaces from Thinking Machines Lab, showing models producing interactive interfaces rather than text responses. Watch it next to the Google Research generative UI work to see how differently two labs are framing the same capability, and what each treats as the hard problem - rendering fidelity, latency, or user control. Short, visual, and easy to use as a discussion prompt about who is designing these interfaces.",
    tags: ["LLM","Prototyping","Multimodal Ai"],
    dateAdded: "2026-08-24",
    author: "Thinking Machines Lab",
    year: 2026,
  },
  {
    id: "1787598069388-qkvey9mfi",
    title: "Our AI Design Workflows Have Changed (Again)",
    type: "video",
    url: "https://www.youtube.com/watch?v=j_ytmrYU_zc",
    thumbnail: "https://img.youtube.com/vi/j_ytmrYU_zc/maxresdefault.jpg",
    summary: "Kyle Zantos walks through how his team's day-to-day AI design workflow has been rebuilt, covering which tools survived contact with real projects, where coding agents replaced design-specific AI tools, and what handoff looks like when the prototype is the spec. Candid about what did not work, which is rarer and more useful than another tool tour. A good companion to the 2026 AI Design Field Report.",
    tags: ["Vibe Coding","Prototyping","Careers"],
    dateAdded: "2026-08-24",
    author: "Kyle Zantos on Dive Club",
    year: 2026,
  }
]

export function getPopularTags(items: Resource[]): TagWithCount[] {
  const tagCounts: { [key: string]: number } = {}

  items.forEach((item) => {
    item.tags?.forEach((tag) => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1
    })
  })

  return Object.entries(tagCounts)
    .map(([tag, count]) => ({ tag, count }))
    .filter(({ count }) => count > POPULAR_TAG_MIN_REFERENCES)
    .sort((a, b) => b.count - a.count)
}

export function getAllTags(items: Resource[]): TagWithCount[] {
  const tagCounts: { [key: string]: number } = {}

  items.forEach((item) => {
    item.tags?.forEach((tag) => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1
    })
  })

  return Object.entries(tagCounts)
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => a.tag.localeCompare(b.tag))
}
